#!/usr/bin/env php
<?php

use Composer\XdebugHandler\XdebugHandler;
use Deptrac\Deptrac\Supportive\Console\Application;

if (PHP_VERSION_ID < 80100) {
    echo 'Required at least PHP version 8.1.0, your version: '.PHP_VERSION."\n";
    exit(1);
}

if (isset($GLOBALS['_composer_autoload_path'])) {
    define('DEPTRAC_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);
} else {
    foreach ([__DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php', __DIR__.'/vendor/autoload.php'] as $file) {
        if (file_exists($file)) {
            define('DEPTRAC_COMPOSER_INSTALL', $file);

            break;
        }
    }

    unset($file);
}

if (!defined('DEPTRAC_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:'.PHP_EOL.PHP_EOL.
        '    composer install'.PHP_EOL.PHP_EOL.
        'You can learn all about Composer on https://getcomposer.org/.'.PHP_EOL
    );

    exit(1);
}

require_once DEPTRAC_COMPOSER_INSTALL;

$xdebug = new XdebugHandler('DEPTRAC');
$xdebug->check();
unset($xdebug);

(new Application())->run();
